language: node_js
node_js:
  - "7.8"
addons:
  sauce_connect:
    username: "layer-ui-web"
  jwt:
    secure: "CycKDIZhY4drsdjuJ5FAnMHLsPoy9NqQ/fEIqOLIHeeJQ+lLNH+1Fi3877BtsUwxIcf7N+fMOg3ljLFuYxj7NliAmzsM4jLTFjWLn6RR2N3cSkVK/mVQn+lTVLMr1V1+s8rD+IyRcEGbXjdhmON/CClUsQqiVvB5Oq9TA9Oh3gG96+W2RAmE1q8ZvFdbAoHiuzH9jimf4Wij1ZIRWuxqEM24gYkFC5hcP9f7ujt4WHRNFHzDWzuwVTKxhLpVXcoOt6h7fzt9JvgsOORlNjSbWtzVnmIo7FaimdpSIjwLqCRjpu1ZYxJb//cZknZ3OYmhZ1s2aLchI6zESKzBG4pOJARwNHcswyBMgD3eFKCaOnDDwPF/cyYDkJssMRfx9cv9O2IXVbzl++wMq6MWR726WS1oNpSumyuQtCs9x7ChUptQcry/lPLKbU4ihkN/03tS2TzA08vrfKdxzopNUwKqlIBgCpGBJL3RBwmVKHxQvInNfvk8WfpdJGYZNp21ko8rY0RnJaV/UN1mH7opUA1O0one6pDAh6QPbncUJEpbHf5ARGP8jngJ32ltHMcKHrYory+MZtHtAdbWxm/yMmGSAzlaGUajQ/RIyTEM7p3X/n4pFcaGUSiaN0jaHNojbZbi2In3xmiB/zgji+pn4g845/YK0RGznqaDWAk3DnH0YZk="