language: node_js
node_js:
- '7.8'
addons:
  sauce_connect:
    username: layer-ui-web
  jwt:
    secure: WwfOWf/gCvnjEexuI4p5Bx82z5i8TNePGq7V+50qAscNl8UV2noLLqtTguwdjkARiySYDpfXgyjLcGwHQs8o7g3xS/w61NJTtKpuf8pR+gRpJNkKJU+/94nIDuisZlcEMr+p3nw8125llKM7rE7qSFCTWPkOVGn2kimO5fom/p6ZX7stxVdrNuSfTvG6Z8IzppvXc3qWtq7rKk3UbACjq7nTLaprJXFkSBLtm9ixecEnlQ5biLobh/3Rn3tGNd74mdSWnvoYakxLQahExFIZfPwhbwf4vxIH+Y+znSK/ZnBK//DIb16Q8Jyew3t/7zyvszPVYR5IBPdwdopIJRlclCpB9kwM+j1AIxCh28Fs516lM2z/bTFNqa3lsyfRXpftLKtIyreVDT0iJQq+0I4Bcn/R62n9T/wo3iJyjM03vQGTGRVI1YFlvM76KD1Uuo1oba5J7QuZLavXU5+I6k+udxKH8pbI/t3A9ZfkaQoj9w9djiPQXkfHOxHSOINPAjEIa/BbCLRMhYgmbZsyz1i3duknkeChiTqtE3fkzYCUZ6n23yTrha/MFYHmjD1dPtyDjywGnxfk/PaDaEJPipvK9bNBjXDoFWXJ/pnCPCc90h7i0iNMGWzcLiykip9eNi4L0MlKU8ZMFDcJ9BBFT0v5OIfCTHhaXMVldOzyTfmsQ6k=
