language: node_js
node_js:
- '7.8'
addons:
  sauce_connect:
    username: layer-ui-web
env:
  global:
    secure: HXTGHCNuREIDVC3EwBzK8cHADHMAOcYspgXTTLgfCLPLurRasrLVPqoM45uWuH/yfXLoVRwgUKwFgPE2eydjCbTfay2cVKWHp1I5j/Idxwt96xdaxzbs7uJ/SVFVCE/3RAu9HNGzU4DPy2IwPYkgxA9qHO981ki6XUYs31VbPw7nk7LppLuAavNFanU78ANBUNSxtuq8B7Uhok1z2+r0cdxIu8OFnEJvh5JJITnFGep6NqkjnegOjKqIAwkfMYHOz1r184wK/vTy2IPv2OfXFuSnWzLU/kPxOf/+y7IXq3e2Icb4x8tOqpcKazKipL/s8z76z7xyNwKA1zJAh40leOWafIGxgJHQnW9vATAazjgEFYcl1eA15HbGaRbqBs4LrbMH8Y+zyIUyvMNxj6k1l8OyFUBn+9RlD/lgeM8AEONskuGYpdfOzr0zJFVWo0knBWPn2+S5vXDziidPwyHvAIscT4SbPh7FOv0ESRyE983VWX0VVbqqonXbzzUsek/wfLnABPgLTOYOQvcrwv0gNb1VBMH9Ke3TT0/YVZIAmRP6YSxIG/AFiH1gJLu0EJGUXZ/JBuG0v8nAuyvI7cbTU8i6WM8m7QPsmKAI9yVD4y/5H1/R5ne/c7igDOZd3PwT+/mQCDeYMH4uPlr8mvgLVePbsv9Hd5Aypv/wVEDfxfo=
