version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-deps-{{ .Branch }}-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}

      - run: wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz

      - run: tar -xzf sc-latest-linux.tar.gz

      - run: nohup bash -c "cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --readyfile ~/sauce_is_ready"

      # Wait for tunnel to be ready
      - while [ ! -e ~/sauce_is_ready ]; do sleep 1; done

      - run:  ./node_modules/grunt/bin/grunt test
